/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface BaseLocation {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  name_ko: string | null;
  sort_order: Generated<number>;
}

export interface CalendarEvent {
  category: Generated<string>;
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: number;
  date: Timestamp;
  description: string | null;
  end_date: Timestamp | null;
  end_time: string | null;
  id: Generated<number>;
  is_all_day: Generated<boolean>;
  location: string | null;
  property_id: number | null;
  start_time: string | null;
  tenant_id: number | null;
  title: string;
  updated_at: Generated<Timestamp>;
  urgency: Generated<string>;
}

export interface CalendarEventAttendee {
  attendee_id: string;
  attendee_type: string;
  created_at: Generated<Timestamp>;
  event_id: number;
  id: Generated<number>;
}

export interface Document {
  comments: string | null;
  created_at: Generated<Timestamp>;
  entity_id: number;
  entity_type: string;
  file_name: string;
  file_type: string;
  file_url: string;
  id: Generated<number>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  uploaded_by: number;
}

export interface EventCategory {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  icon: string;
  id: Generated<number>;
  is_default: Generated<boolean>;
  label: string;
  sort_order: Generated<number>;
  value: string;
}

export interface ExchangeRate {
  created_at: Generated<Timestamp>;
  date: Timestamp;
  denomination: Generated<number>;
  id: Generated<number>;
  set_by: number;
  updated_at: Generated<Timestamp>;
  usd_to_krw: Numeric;
}

export interface Landlord {
  bank_account: string | null;
  bank_name: string | null;
  birth: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  email: string | null;
  id: Generated<number>;
  name: string;
  notes: string | null;
  phone: string;
  sex: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LandlordFamilyMember {
  birth: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  landlord_id: number;
  name: string;
  notes: string | null;
  phone: string | null;
  relationship: string;
  sex: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Lease {
  created_at: Generated<Timestamp>;
  created_by: number | null;
  deposit_krw: Numeric;
  end_date: Timestamp;
  id: Generated<number>;
  monthly_rent_krw: Numeric;
  notes: string | null;
  property_id: number;
  start_date: Timestamp;
  status: Generated<string>;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface LedgerEntry {
  amount_krw: Numeric;
  category: string;
  created_at: Generated<Timestamp>;
  description: string;
  entry_date: Timestamp;
  entry_type: string;
  id: Generated<number>;
  payment_id: number | null;
  recorded_by: number;
  reference_id: number | null;
  reference_type: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Payment {
  amount_krw: Numeric;
  amount_paid: Numeric;
  bill_paid: Generated<boolean>;
  bill_paid_at: Timestamp | null;
  bill_paid_by: number | null;
  billing_month: Timestamp;
  bundle_id: string | null;
  created_at: Generated<Timestamp>;
  currency_paid: string;
  exchange_rate_id: number | null;
  id: Generated<number>;
  lease_id: number;
  notes: string | null;
  paid_by_family_member_id: number | null;
  paid_by_tenant: Generated<boolean>;
  payment_date: Timestamp;
  payment_method: string;
  payment_type: string;
  received_by: number;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Property {
  address: string;
  address_detail: string | null;
  address_en: string | null;
  bathrooms: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  deposit_krw: Numeric;
  id: Generated<number>;
  landlord_id: number;
  management_phone: string | null;
  monthly_rent_krw: Numeric;
  notes: string | null;
  permission_status: Generated<string>;
  property_type: string;
  rooms: number | null;
  size_pyeong: Numeric | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PropertyEquipment {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  monthly_cost_krw: Generated<Numeric>;
  name: string;
  notes: string | null;
  paid_by: string;
  property_id: number;
  updated_at: Generated<Timestamp>;
}

export interface ServiceCategory {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_default: Generated<boolean>;
  label: string;
  sort_order: Generated<number>;
  value: string;
}

export interface ServiceRequest {
  category: string;
  cost_krw: Numeric | null;
  created_at: Generated<Timestamp>;
  description: string;
  escalated_to_landlord: Generated<boolean>;
  id: Generated<number>;
  lease_id: number;
  logged_by: number;
  notes: string | null;
  resolved_at: Timestamp | null;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface ServiceRequestStatusLog {
  changed_by: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  note: string | null;
  service_request_id: number;
  status: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: number;
}

export interface Tenant {
  base_location_id: number;
  birth: Timestamp | null;
  branch: string | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  deros: Timestamp | null;
  email: string | null;
  id: Generated<number>;
  name: string;
  notes: string | null;
  phone: string;
  rank: string | null;
  sex: string | null;
  status: Generated<string>;
  unit: string | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantFamilyMember {
  base_location_id: number | null;
  birth: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  notes: string | null;
  phone: string | null;
  relationship: string;
  sex: string | null;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface TenantNote {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: number;
  id: Generated<number>;
  tenant_id: number;
}

export interface TenantPet {
  breed: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  notes: string | null;
  size: string | null;
  species: string;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  calendar_token: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: Generated<number>;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface UtilityBill {
  amount_krw: Numeric;
  billing_month: Timestamp;
  created_at: Generated<Timestamp>;
  due_date: Timestamp | null;
  id: Generated<number>;
  lease_id: number;
  notes: string | null;
  paid_to_company: Generated<boolean>;
  paid_to_company_date: Timestamp | null;
  payment_id: number | null;
  updated_at: Generated<Timestamp>;
  utility_type_id: number;
}

export interface UtilityType {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_default: Generated<boolean>;
  name: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  base_location: BaseLocation;
  calendar_event: CalendarEvent;
  calendar_event_attendee: CalendarEventAttendee;
  document: Document;
  event_category: EventCategory;
  exchange_rate: ExchangeRate;
  landlord: Landlord;
  landlord_family_member: LandlordFamilyMember;
  lease: Lease;
  ledger_entry: LedgerEntry;
  payment: Payment;
  property: Property;
  property_equipment: PropertyEquipment;
  service_category: ServiceCategory;
  service_request: ServiceRequest;
  service_request_status_log: ServiceRequestStatusLog;
  session: Session;
  tenant: Tenant;
  tenant_family_member: TenantFamilyMember;
  tenant_note: TenantNote;
  tenant_pet: TenantPet;
  user: User;
  utility_bill: UtilityBill;
  utility_type: UtilityType;
  verification: Verification;
}
